export default {
  FETCH_OVERVIEW_DATA: 'FETCH_OVERVIEW_DATA',
  FETCH_SALDO_DATA: 'FETCH_SALDO_DATA',
  SET_SPENDINGS_DATA: 'SET_SPENDINGS_DATA',
  SET_TODAY_SPENDINGS_SUM: 'SET_TODAY_SPENDINGS_SUM',
  SET_TOTAL_INCOMES_DATA: 'SET_TOTAL_INCOMES_DATA',
  SET_TOTAL_COSTS_DATA: 'SET_TOTAL_COSTS_DATA',
  SET_TOTAL_DATE: 'SET_TOTAL_DATE',
};
