export default {
  SET_USER_INFO: 'SET_USER_INFO',
  SET_IS_FETCH_FAILED: 'SET_IS_FETCH_FAILED',
  RESET_STORE: 'RESET_STORE',
  SET_INCOMES_DATA: 'SET_INCOMES_DATA',
  SET_COSTS_DATA: 'SET_COSTS_DATA',
  SET_DAY_SPENDINGS_DATA: 'SET_DAY_SPENDINGS_DATA',
  SET_MONTH_SPENDINGS_DATA: 'SET_MONTH_SPENDINGS_DATA',
  SET_SAVINGS: 'SET_SAVINGS',
  SET_CURRENT_MONTH: 'SET_CURRENT_MONTH',
  SET_OVERVIEW_DATA: 'SET_OVERVIEW_DATA',
  SET_DATE: 'SET_DATE',
  SET_USER_ACCESS_TOKEN: 'SET_USER_ACCESS_TOKEN',
};
