export default {
  SET_USER_INFO: 'SET_USER_INFO',
  SET_IS_FETCH_FAILED: 'SET_IS_FETCH_FAILED',
  RESET_STORE: 'RESET_STORE',
  SET_INCOMES_DATA: 'SET_INCOMES_DATA',
  SET_COSTS_DATA: 'SET_COSTS_DATA',
  SET_DAY_SPENDINGS_DATA: 'SET_DAY_SPENDINGS_DATA',
  SET_MOUNTH_SPENDINGS_DATA: 'SET_MOUNTH_SPENDINGS_DATA',
  SET_SAVINGS: 'SET_SAVINGS',
  SET_CURRENT_MOUNTH: 'SET_CURRENT_MOUNTH',
  SET_OVERVIEW_DATA: 'SET_OVERVIEW_DATA',
  SET_DATE: 'SET_DATE',
};
